services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: web
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
