services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: frontend
    container_name: web
    depends_on: 
      backend:
        condition: service_started
        restart: true
    networks:
      - app-network
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: backend
    container_name: api
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - app-network
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge